platform :ios, '10.3'

target 'OneSignalDemo' do
    pod 'OneSignal', :git => 'https://github.com/marvin-yorke/OneSignal-iOS-SDK', :branch => 'master'
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', :git => 'https://github.com/marvin-yorke/OneSignal-iOS-SDK', :branch => 'master'
end
