public let anonUserOSID = "test_anon_user_onesignal_id"
public let userA_OSID = "test_user_a_onesignal_id"
public let userA_EUID = "test_user_a_external_id"
public let userB_OSID = "test_user_b_onesignal_id"
public let userB_EUID = "test_user_b_external_id"
