platform :ios, '10.3'

target 'OneSignalDemo' do
  pod 'OneSignal', :git => 'https://github.com/OneSignal/OneSignal-iOS-SDK.git', :branch => 'major_release_3.0.0'
end

target 'NotificationServiceExtension' do
  pod 'OneSignal', :git => 'https://github.com/OneSignal/OneSignal-iOS-SDK.git', :branch => 'major_release_3.0.0'
end
